import type { Transaction } from "../types/types";

export const CATEGORIES = [
  { value: "food", label: "Food" },
  { value: "transport", label: "Transport" },
  { value: "shopping", label: "Shopping" },
  { value: "health", label: "Health" },
  { value: "entertainment", label: "Entertainment" },
  { value: "salary", label: "Salary" },
];

export const FILTER_CATEGORIES = [
  { value: "all", label: "All Categories" },
  ...CATEGORIES,
];

export const CATEGORY_COLORS: Record<string, string> = {
    food: "bg-red-500",
    transport: "bg-blue-500",
    shopping: "bg-purple-500",
    health: "bg-green-500",
    entertainment: "bg-pink-500",
    salary: "bg-emerald-500",
    utilities: "bg-violet-500",
  };

export const CATEGORY_DOT_COLORS: Record<string, string> = {
    food: "bg-red-400",
    transport: "bg-blue-400",
    shopping: "bg-purple-400",
    health: "bg-green-400",
    entertainment: "bg-pink-400",
    salary: "bg-emerald-400",
    utilities: "bg-violet-400",
  };

export const SUGGESTIONS = [
    "What's my biggest expense category?",
    "How much have I spent in total?",
    "What's my income vs expenses ratio?",
    "Where can I cut back on spending?",
  ];

export const dummyTransactions: Transaction[] = [
  {
    id: "1",
    type: "expense",
    title: "New Year's Eve Party",
    description: "Party supplies and decorations",
    amount: "150.45",
    date: "2023-12-31",
    category: "Entertainment",
  },
  {
    id: "2",
    type: "income",
    title: "Monthly Salary",
    description: "January paycheck",
    amount: "3500.00",
    date: "2024-01-01",
    category: "Salary",
  },
  {
    id: "3",
    type: "expense",
    title: "Grocery Run",
    description: "Weekly groceries from Walmart",
    amount: "87.32",
    date: "2024-01-05",
    category: "Food",
  },
  {
    id: "4",
    type: "expense",
    title: "Uber to Airport",
    description: "Ride to JFK terminal 4",
    amount: "42.00",
    date: "2024-01-08",
    category: "Transport",
  },
  {
    id: "5",
    type: "expense",
    title: "Netflix Subscription",
    description: "Monthly streaming plan",
    amount: "15.99",
    date: "2024-01-10",
    category: "Entertainment",
  },
  {
    id: "6",
    type: "income",
    title: "Freelance Project",
    description: "Logo design for client",
    amount: "750.00",
    date: "2024-01-12",
    category: "Salary",
  },
  {
    id: "7",
    type: "expense",
    title: "Doctor Visit",
    description: "Annual checkup co-pay",
    amount: "60.00",
    date: "2024-01-15",
    category: "Health",
  },
  {
    id: "8",
    type: "expense",
    title: "Amazon Order",
    description: "Phone case and charger",
    amount: "34.99",
    date: "2024-01-18",
    category: "Shopping",
  },
  {
    id: "9",
    type: "expense",
    title: "Electric Bill",
    description: "January utility bill",
    amount: "112.80",
    date: "2024-01-20",
    category: "Utilities",
  },
  {
    id: "10",
    type: "income",
    title: "Stock Dividend",
    description: "Q4 dividend payout",
    amount: "220.50",
    date: "2024-01-22",
    category: "Salary",
  },
  {
    id: "1",
    type: "expense",
    title: "New Year's Eve Party",
    description: "Party supplies and decorations",
    amount: "150.45",
    date: "2023-12-31",
    category: "Entertainment",
  },
  {
    id: "2",
    type: "income",
    title: "Monthly Salary",
    description: "January paycheck",
    amount: "3500.00",
    date: "2024-01-01",
    category: "Salary",
  },
  {
    id: "3",
    type: "expense",
    title: "Grocery Run",
    description: "Weekly groceries from Walmart",
    amount: "87.32",
    date: "2024-01-05",
    category: "Food",
  },
  {
    id: "4",
    type: "expense",
    title: "Uber to Airport",
    description: "Ride to JFK terminal 4",
    amount: "42.00",
    date: "2024-01-08",
    category: "Transport",
  },
  {
    id: "5",
    type: "expense",
    title: "Netflix Subscription",
    description: "Monthly streaming plan",
    amount: "15.99",
    date: "2024-01-10",
    category: "Entertainment",
  },
  {
    id: "6",
    type: "income",
    title: "Freelance Project",
    description: "Logo design for client",
    amount: "750.00",
    date: "2024-01-12",
    category: "Salary",
  },
  {
    id: "7",
    type: "expense",
    title: "Doctor Visit",
    description: "Annual checkup co-pay",
    amount: "60.00",
    date: "2024-01-15",
    category: "Health",
  },
  {
    id: "8",
    type: "expense",
    title: "Amazon Order",
    description: "Phone case and charger",
    amount: "34.99",
    date: "2024-01-18",
    category: "Shopping",
  },
  {
    id: "9",
    type: "expense",
    title: "Electric Bill",
    description: "January utility bill",
    amount: "112.80",
    date: "2024-01-20",
    category: "Utilities",
  },
  {
    id: "10",
    type: "income",
    title: "Stock Dividend",
    description: "Q4 dividend payout",
    amount: "220.50",
    date: "2024-01-22",
    category: "Salary",
  },
];
